language: python
python:
    - "2.7"

sudo: false
cache:
    directories:
        - "~/.platformio"

env:
    - PLATFORMIO_CI_SRC=test/test_main.cpp

install:
    - pip install -U platformio
    - platformio update

script:
    - echo "Run desktop (native) tests on Travis.CI Linux machine"
    - platformio test --verbose --environment native_test
